name: Code Formatting

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.java'

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Format Java code
      uses: axel-op/googlejavaformat-action@v3
      with:
        args: "--aosp --replace"
        skip-commit: true

    - name: Apply .editorconfig rules
      run: |
        find src -name "*.java" -type f -exec sed -i 's/\r$//' {} \;
        find src -name "*.java" -type f -exec sed -i 's/[[:space:]]*$//' {} \;
        find src -name "*.java" -type f -exec sh -c 'if [ -n "$(tail -c1 "$1")" ]; then echo >> "$1"; fi' _ {} \;

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "style: format Java code according to .editorconfig"
        file_pattern: "src/**/*.java"
