name: Code Formatting

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.java'

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Format Java code
      uses: axel-op/googlejavaformat-action@v3
      with:
        args: "--aosp --replace"
        skip-commit: true

    - name: Apply .editorconfig rules
      uses: editorconfig-checker/action-editorconfig-checker@v2
      with:
        flags: '--fix'

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "style: format Java code according to .editorconfig"
        file_pattern: "src/**/*.java"
