name: Code Formatting

on:
  push:
    paths:
      - "**/*.java"
  pull_request:
    paths:
      - "**/*.java"

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check formatting with Spotless
        run: ./gradlew spotlessCheck
        continue-on-error: true

      - name: Apply formatting with Spotless
        run: ./gradlew spotlessApply

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "style: format Java code with Google Java Format via Spotless"
          file_pattern: "src/**/*.java"

      - name: Comment on PR if formatting needed
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Code formatting issues detected. Please run `./gradlew spotlessApply` locally and commit the changes.'
            })
